import { Audit, Expense, Payment, Role, User, assertImage, contributionSummary, hashPassword, newId, normalizeName, temporaryPassword, verifyPassword } from './domain';
export class AppError extends Error{constructor(message:string,public status=400){super(message)}}
type Photo={id:string;album_id?:string|null;path:string;title:string;created_by:string;created_at:string}; type Album={id:string;name:string;created_at:string};
export class MemoryStore{users:User[]=[];payments:Payment[]=[];expenses:Expense[]=[];audits:Audit[]=[];photos:Photo[]=[];albums:Album[]=[];totalBudget=500000;loginAttempts=new Map<string,{count:number;reset:number}>();
now(){return new Date().toISOString()} audit(actor:string|null,action:string,entity_type:string,entity_id:string,metadata:Record<string,unknown>={}){this.audits.unshift({id:newId('aud'),actor_id:actor,action,entity_type,entity_id,metadata,created_at:this.now()})}
async bootstrap(){if(this.users.length)return;const g=await this.createUser(null,'Gokul','SUPER_ADMIN',0,process.env.INITIAL_GOKUL_PASSWORD||'GokulDev123!');const gokul=g.user;await this.createUser(gokul.id,'Surya','ADMIN',0,process.env.INITIAL_SURYA_PASSWORD||'SuryaDev123!');await this.createUser(gokul.id,'Ananya','FRIEND',10000,'FriendDev123!');await this.createExpense(gokul.id,{amount:12500,category:'Food',description:'Dinner catering',notes:'Seed'});this.albums.push({id:newId('alb'),name:'Wedding Prep',created_at:this.now()})}
getUser(id:string){return this.users.find(u=>u.id===id)} requireUser(id:string){const u=this.getUser(id); if(!u)throw new AppError('User not found',404); return u} requireAdmin(actor:User){if(!['ADMIN','SUPER_ADMIN'].includes(actor.role))throw new AppError('Admin access required',403)} requireSuper(actor:User){if(actor.role!=='SUPER_ADMIN')throw new AppError('Only Gokul can approve or reject payments',403)}
async createUser(actorId:string|null,name:string,role:Role='FRIEND',required=0,password?:string){const n=normalizeName(name); if(!n||n.length>80)throw new AppError('Enter a valid name.'); if(this.users.some(u=>u.name_normalized===n))throw new AppError('A profile with this name already exists.',409); if(required<0)throw new AppError('Contribution cannot be negative.'); const pass=password||temporaryPassword(); const u:User={id:newId('usr'),name:name.trim().replace(/\s+/g,' '),name_normalized:n,role,password_hash:await hashPassword(pass),must_change_password:role==='FRIEND',required_contribution:required,created_at:this.now()};this.users.push(u);this.audit(actorId,'user.created','user',u.id,{role});return{user:u,temporaryPassword:pass}}
async resetPassword(actor:User,userId:string){this.requireAdmin(actor);const pw=temporaryPassword();const u=this.requireUser(userId);u.password_hash=await hashPassword(pw);u.must_change_password=true;this.audit(actor.id,'password.reset','user',u.id,{});return pw}
async login(name:string,password:string,ip='local'){const key=`${normalizeName(name)}:${ip}`, hit=this.loginAttempts.get(key); if(hit&&hit.count>=8&&hit.reset>Date.now())throw new AppError('Too many login attempts. Try again later.',429); const u=this.users.find(x=>x.name_normalized===normalizeName(name)); if(!u||!(await verifyPassword(password,u.password_hash))){this.loginAttempts.set(key,{count:(hit?.count??0)+1,reset:Date.now()+15*60_000});throw new AppError('Invalid name or password.',401)} this.loginAttempts.delete(key); return u}
async changePassword(user:User,newPassword:string){if(newPassword.length<8)throw new AppError('Password must be at least 8 characters.'); user.password_hash=await hashPassword(newPassword); user.must_change_password=false; this.audit(user.id,'password.changed','user',user.id,{})}
async updateProfilePhoto(actor:User,userId:string,file:{type:string;size:number;name:string}){if(actor.id!==userId&&!['ADMIN','SUPER_ADMIN'].includes(actor.role))throw new AppError('Cannot update another profile.',403);assertImage(file);const u=this.requireUser(userId);u.profile_photo_path=`profile-photos/${u.id}/${crypto.randomUUID()}-${file.name.replace(/[^a-z0-9.]/gi,'')}`;this.audit(actor.id,'profile.photo.updated','user',u.id,{});return u.profile_photo_path}
async submitPayment(actor:User,amount:number,file:{type:string;size:number;name:string},idempotencyKey:string,notes?:string){if(amount<=0||amount>1000000)throw new AppError('Enter a valid payment amount.'); if(!idempotencyKey)throw new AppError('Missing idempotency key.'); assertImage(file); const existing=this.payments.find(p=>p.user_id===actor.id&&p.idempotency_key===idempotencyKey); if(existing)return existing; const p:Payment={id:newId('pay'),user_id:actor.id,amount,status:'PENDING',screenshot_path:`payment-proofs/${actor.id}/${crypto.randomUUID()}-${file.name}`,notes,idempotency_key:idempotencyKey,created_at:this.now()};this.payments.push(p);this.audit(actor.id,'payment.submitted','payment',p.id,{amount});return p}
async approvePayment(actor:User,id:string){this.requireSuper(actor);const p=this.payments.find(x=>x.id===id); if(!p)throw new AppError('Payment not found',404); if(p.status!=='PENDING')throw new AppError('Only pending payments can be approved.',409); p.status='APPROVED';p.approved_at=this.now();p.approved_by=actor.id;this.audit(actor.id,'payment.approved','payment',p.id,{amount:p.amount});return p}
async rejectPayment(actor:User,id:string,reason:string){this.requireSuper(actor);const p=this.payments.find(x=>x.id===id); if(!p)throw new AppError('Payment not found',404); if(p.status!=='PENDING'&&p.status!=='REJECTED')throw new AppError('Approved payments are immutable.',409); p.status='REJECTED';p.rejected_at=this.now();p.rejected_by=actor.id;p.rejection_reason=reason;this.audit(actor.id,'payment.rejected','payment',p.id,{reason});return p}
async createExpense(actorId:string,data:{amount:number;category:string;description:string;notes?:string}){const actor=this.requireUser(actorId);this.requireAdmin(actor); if(data.amount<=0)throw new AppError('Expense amount must be positive.'); const e:Expense={id:newId('exp'),amount:data.amount,category:data.category,description:data.description,notes:data.notes,created_by:actor.id,created_at:this.now(),updated_at:this.now()};this.expenses.push(e);this.audit(actor.id,'expense.created','expense',e.id,{amount:e.amount,category:e.category});return e}
summary(user:User){return contributionSummary(user,this.payments.filter(p=>p.user_id===user.id))}
}
export const store=new MemoryStore();
