-- Development-only seed data. Admin password hashes must be generated by scripts/seed-admins.ts or your own secure process.
insert into application_settings(id,total_budget) values (1,500000) on conflict(id) do update set total_budget=excluded.total_budget;
insert into albums(name) values ('Wedding Prep'),('College Days'),('Trips'),('Friends'),('Random Chaos') on conflict do nothing;
