create type app_role as enum ('SUPER_ADMIN','ADMIN','FRIEND');
create type payment_status as enum ('PENDING','APPROVED','REJECTED');

create table app_users(id uuid primary key default gen_random_uuid(),name text not null,name_normalized text not null unique,role app_role not null default 'FRIEND',password_hash text not null,must_change_password boolean not null default true,required_contribution numeric(12,2) not null default 0 check(required_contribution>=0),bio text,profile_photo_path text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table payments(id uuid primary key default gen_random_uuid(),user_id uuid not null references app_users(id),amount numeric(12,2) not null check(amount>0),status payment_status not null default 'PENDING',screenshot_path text not null,notes text,method text,reference_id text,idempotency_key text not null,approved_at timestamptz,approved_by uuid references app_users(id),rejected_at timestamptz,rejected_by uuid references app_users(id),rejection_reason text,created_at timestamptz not null default now(),unique(user_id,idempotency_key));
create table expenses(id uuid primary key default gen_random_uuid(),amount numeric(12,2) not null check(amount>0),category text not null,description text not null,notes text,created_by uuid not null references app_users(id),deleted_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table albums(id uuid primary key default gen_random_uuid(),name text not null unique,created_at timestamptz not null default now());
create table photos(id uuid primary key default gen_random_uuid(),album_id uuid references albums(id),path text not null,title text not null,created_by uuid references app_users(id),created_at timestamptz not null default now());
create table audit_logs(id uuid primary key default gen_random_uuid(),actor_id uuid references app_users(id),action text not null,entity_type text not null,entity_id uuid not null,metadata jsonb not null default '{}',created_at timestamptz not null default now());
create table application_settings(id integer primary key default 1 check(id=1),total_budget numeric(12,2) not null default 0 check(total_budget>=0),updated_at timestamptz not null default now(),updated_by uuid references app_users(id));
create table login_attempts(attempt_key text primary key,attempt_count integer not null default 0,reset_at timestamptz not null);
insert into application_settings(id,total_budget) values (1,0) on conflict (id) do nothing;

create index idx_payments_user on payments(user_id); create index idx_payments_status on payments(status); create index idx_payments_created on payments(created_at desc); create index idx_expenses_category on expenses(category); create index idx_expenses_created on expenses(created_at desc); create index idx_photos_album on photos(album_id); create index idx_audit_created on audit_logs(created_at desc); create index idx_login_attempts_reset on login_attempts(reset_at);

create view user_contribution_summaries as select u.id as user_id,coalesce(sum(p.amount) filter (where p.status='APPROVED'),0) approved_paid,coalesce(sum(p.amount) filter (where p.status='PENDING'),0) pending_amount from app_users u left join payments p on p.user_id=u.id group by u.id;
create view expense_category_totals as select category,coalesce(sum(amount),0) total from expenses where deleted_at is null group by category;

create function audit(p_actor_id uuid,p_action text,p_entity_type text,p_entity_id uuid,p_metadata jsonb default '{}') returns void language sql security definer as $$ insert into audit_logs(actor_id,action,entity_type,entity_id,metadata) values (p_actor_id,p_action,p_entity_type,p_entity_id,p_metadata); $$;
create function record_login_failure(p_attempt_key text) returns void language sql security definer as $$ insert into login_attempts(attempt_key,attempt_count,reset_at) values (p_attempt_key,1,now()+interval '15 minutes') on conflict(attempt_key) do update set attempt_count=case when login_attempts.reset_at<now() then 1 else login_attempts.attempt_count+1 end, reset_at=case when login_attempts.reset_at<now() then now()+interval '15 minutes' else login_attempts.reset_at end; $$;
create function create_friend_with_audit(p_actor_id uuid,p_name text,p_name_normalized text,p_password_hash text,p_required_contribution numeric,p_bio text) returns app_users language plpgsql security definer as $$ declare created app_users; begin insert into app_users(name,name_normalized,role,password_hash,must_change_password,required_contribution,bio) values (p_name,p_name_normalized,'FRIEND',p_password_hash,true,p_required_contribution,p_bio) returning * into created; perform audit(p_actor_id,'user.created','user',created.id,jsonb_build_object('role','FRIEND')); return created; end; $$;
create function reset_password_with_audit(p_actor_id uuid,p_user_id uuid,p_password_hash text) returns void language plpgsql security definer as $$ begin update app_users set password_hash=p_password_hash,must_change_password=true,updated_at=now() where id=p_user_id; if not found then raise exception 'not_found'; end if; perform audit(p_actor_id,'password.reset','user',p_user_id,'{}'); end; $$;
create function change_password_with_audit(p_user_id uuid,p_password_hash text) returns void language plpgsql security definer as $$ begin update app_users set password_hash=p_password_hash,must_change_password=false,updated_at=now() where id=p_user_id; if not found then raise exception 'not_found'; end if; perform audit(p_user_id,'password.changed','user',p_user_id,'{}'); end; $$;
create function update_profile_photo_with_audit(p_actor_id uuid,p_user_id uuid,p_path text) returns void language plpgsql security definer as $$ begin update app_users set profile_photo_path=p_path,updated_at=now() where id=p_user_id; if not found then raise exception 'not_found'; end if; perform audit(p_actor_id,'profile.photo.updated','user',p_user_id,jsonb_build_object('path',p_path)); end; $$;
create function submit_payment_with_audit(p_user_id uuid,p_amount numeric,p_screenshot_path text,p_notes text,p_method text,p_reference_id text,p_idempotency_key text) returns payments language plpgsql security definer as $$ declare created payments; begin insert into payments(user_id,amount,status,screenshot_path,notes,method,reference_id,idempotency_key) values (p_user_id,p_amount,'PENDING',p_screenshot_path,p_notes,p_method,p_reference_id,p_idempotency_key) on conflict(user_id,idempotency_key) do update set idempotency_key=excluded.idempotency_key returning * into created; perform audit(p_user_id,'payment.submitted','payment',created.id,jsonb_build_object('amount',created.amount)); return created; end; $$;
create function approve_payment_with_audit(p_actor_id uuid,p_payment_id uuid) returns payments language plpgsql security definer as $$ declare updated payments; begin update payments set status='APPROVED',approved_at=now(),approved_by=p_actor_id where id=p_payment_id and status='PENDING' returning * into updated; if updated.id is null then raise exception 'invalid_state'; end if; perform audit(p_actor_id,'payment.approved','payment',updated.id,jsonb_build_object('amount',updated.amount)); return updated; end; $$;
create function reject_payment_with_audit(p_actor_id uuid,p_payment_id uuid,p_reason text) returns payments language plpgsql security definer as $$ declare updated payments; begin update payments set status='REJECTED',rejected_at=now(),rejected_by=p_actor_id,rejection_reason=p_reason where id=p_payment_id and status='PENDING' returning * into updated; if updated.id is null then raise exception 'invalid_state'; end if; perform audit(p_actor_id,'payment.rejected','payment',updated.id,jsonb_build_object('reason',p_reason)); return updated; end; $$;
create function create_expense_with_audit(p_actor_id uuid,p_amount numeric,p_category text,p_description text,p_notes text) returns expenses language plpgsql security definer as $$ declare created expenses; begin insert into expenses(amount,category,description,notes,created_by) values (p_amount,p_category,p_description,p_notes,p_actor_id) returning * into created; perform audit(p_actor_id,'expense.created','expense',created.id,jsonb_build_object('amount',created.amount,'category',created.category)); return created; end; $$;
create function update_budget_with_audit(p_actor_id uuid,p_total_budget numeric) returns void language plpgsql security definer as $$ begin update application_settings set total_budget=p_total_budget,updated_at=now(),updated_by=p_actor_id where id=1; perform audit(p_actor_id,'budget.updated','application_settings','00000000-0000-0000-0000-000000000001',jsonb_build_object('total_budget',p_total_budget)); end; $$;
create function create_photo_with_audit(p_actor_id uuid,p_album_id uuid,p_path text,p_title text) returns photos language plpgsql security definer as $$ declare created photos; begin insert into photos(album_id,path,title,created_by) values (p_album_id,p_path,p_title,p_actor_id) returning * into created; perform audit(p_actor_id,'photo.uploaded','photo',created.id,jsonb_build_object('path',p_path)); return created; end; $$;

alter table app_users enable row level security; alter table payments enable row level security; alter table expenses enable row level security; alter table photos enable row level security; alter table albums enable row level security; alter table audit_logs enable row level security; alter table application_settings enable row level security; alter table login_attempts enable row level security;
create policy "service role only users" on app_users using (auth.role()='service_role'); create policy "service role only payments" on payments using (auth.role()='service_role'); create policy "service role only expenses" on expenses using (auth.role()='service_role'); create policy "service role only photos" on photos using (auth.role()='service_role'); create policy "service role only albums" on albums using (auth.role()='service_role'); create policy "service role only audit" on audit_logs using (auth.role()='service_role'); create policy "service role only settings" on application_settings using (auth.role()='service_role'); create policy "service role only login attempts" on login_attempts using (auth.role()='service_role');
